FROM wolnosciowiec/file-repository

ADD .infrastructure/tests_entrypoint.sh /

RUN npm install -g newman \
    && mkdir -p /var/tests \
    && chmod +x /tests_entrypoint.sh

WORKDIR "/var/www/html"

ENTRYPOINT "/tests_entrypoint.sh"
