---
apiVersion: backups.riotkit.org/v1alpha1
kind: BackupUser
metadata:
    name: some-user
spec:
    email: user@riseup.net
    deactivated: false
    organization: "Riotkit"
    about: "Example user"
    password: ""
    passwordFromRef:
        name: backup-repository-passwords
        entry: admin
    accessKeys:
        #
        # login: some-user$uploader
        # password: test
        #
        - name: uploader
          # password: ""
          passwordFromRef:
              name: backup-repository-passwords
              entry: admin_access_key_1
          objects:
              - name: iwa-ait
                type: collection
                roles: ["backupUploader"]
    roles:
        - collectionManager
