version: org.riotkit.rkd/yaml/v1
imports: []
tasks:
    :docker:up:
        become: root
        description: Runs a dockerized environment
        steps: |
            docker rm -f s3pb_db_1
            docker-compose -p s3pb -f .infrastructure/docker/docker-compose.yml up -d --force-recreate
