FROM php:7.4-alpine

{% include ".infrastructure/env-variables.Dockerfile-part" %}

RUN apk add --update bash

RUN set -x \
    && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && mv composer.phar /usr/bin/composer \
    && rm composer-setup.php \
    && chmod +x /usr/bin/composer

RUN set -x \
    && php -m \
    && apk add --no-cache zip libzip-dev rabbitmq-c rabbitmq-c-dev \
    && apk --update add --virtual build-dependencies autoconf gcc g++ make \
    && pecl install redis \
    && pecl install amqp \
    && echo "extension=/usr/local/lib/php/extensions/no-debug-non-zts-20190902/amqp.so" > /usr/local/etc/php/conf.d/amqp.ini \
    && docker-php-ext-install zip bcmath \
    && apk del build-dependencies \
    && rm -rf /var/cache/apk/*

ADD server/.infrastructure/replica/entrypoint*.sh /
ADD server/.infrastructure/healthcheck.sh /
RUN chmod +x /*.sh \
    && addgroup -S riotkit -g 1000 && adduser -S riotkit -u 1000 -G riotkit

ADD server /opt/riotkit/app
RUN chown -R riotkit:riotkit /opt/riotkit/app
WORKDIR "/opt/riotkit/app"

USER riotkit
RUN composer install

HEALTHCHECK --interval=30s --timeout=3s CMD /healthcheck.sh || exit 1
ENTRYPOINT ["./bin/console"]
