secrets:
    BR_JWT_SECRET_KEY: "" # MANDATORY
    BR_DB_HOSTNAME: "postgres.backup-repository.svc.cluster.local"
    BR_DB_PASSWORD: "postgres"
    BR_DB_USERNAME: "postgres"
    BR_DB_NAME: "backup-repository"
    BR_DB_PORT: "5432"

env:
    AWS_SECRET_KEY: "wJaFuCKtnFEMI/CApItaliSM/bPxRfiCYEXAMPLEKEY"
    AWS_ACCESS_KEY_ID: "AKIAIOSFODNN7EXAMPLE"
