version: org.riotkit.rkd/yaml/v1
imports: []

tasks:
    :ci:build-test-environment:
        description: "Builds applications from current commit"
        steps:
            - rkd :server:release:docker-image

    :prepare:integration-environment:
        description: Prepares a full environment with docker containers. Ready for API & E2E testing
        steps:
            - rkd :bahub:env:adapters
            - rkd :server:env:dependencies:up
            - rkd :server:env:server-docker:up --env=test
            - rkd :e2e:install
            - rkd :e2e:browser:spawn-container
            - rkd :bahub:env:bahub-docker:up
            # todo: Wait for E2E browser to get up

    :prepare:local-environment:
        description: Prepares a local unit testing environment
        steps:
            - rkd :bahub:env:adapters
            - rkd :bahub:install
            - rkd :server:install

    :bahub:env:adapters:
        descritpion: Run test services for usage with Bahub
        steps: "cd integration-env && rkd :docker:compose:bahub-dependencies"

    :server:env:db:
        steps: "cd integration-env && rkd :docker:compose:db"

    :bahub:env:bahub-docker:up:
        description: Run a production-like Bahub container
        steps: "cd bahub && rkd :env:bahub-docker:up"

    :server:env:dependencies:up:
        description: Run services required by server
        steps: "cd server && rkd :env:dependencies:up"

    :server:env:server-docker:up:
        description: Run server as production-like docker container
        arguments:
            "--env":
                default: "prod"
        steps: "cd server && rkd :env:server-docker:up --env=${ARG_ENV}"

    :server:release:docker-image:
        description: "Build production-like docker image for server"
        steps: "cd server && rkd :release:docker-image latest"

    :e2e:install:
        description: Install dependencies for E2E tests
        steps: "cd e2e && rkd :install"

    :e2e:browser:spawn-container:
        description: Spawns a docker-container with a browser
        steps: "cd e2e && rkd :browser:spawn-container"
