---
apiVersion: apiextensions.k8s.io/v1
kind: "CustomResourceDefinition"
metadata:
    name: "backupcollections.backups.riotkit.org"
    annotations:
        helm.sh/resource-policy: keep
        argocd.argoproj.io/sync-options: Prune=false
spec:
    group: "backups.riotkit.org"
    scope: "Namespaced"
    names:
        plural: "backupcollections"
        singular: "backupcollection"
        kind: "BackupCollection"
        shortNames:
            - "brcollections"
            - "brc"
        categories:
            - "backuprepository"
    versions:
        - name: v1alpha1
          served: true
          storage: true

          schema:
              openAPIV3Schema:
                  type: object
                  required: ["spec"]
                  properties:
                      spec:
                          type: object
                          required: ["description", "filenameTemplate", "maxBackupsCount", "maxOneVersionSize", "maxCollectionSize", "strategyName", "strategySpec"]
                          properties:
                              description:
                                  type: string
                              filenameTemplate:
                                  type: string
                              maxBackupsCount:
                                  type: integer
                              maxOneVersionSize:
                                  type: string
                                  pattern: '([0-9]+)(B|K|M|G|T)'
                              maxCollectionSize:
                                  type: string
                                  pattern: '([0-9]+)(B|K|M|G|T)'
                              windows:
                                  type: array
                                  items:
                                      type: object
                                      properties:
                                          from:
                                              type: string
                                          duration:
                                              type: string
                                              pattern: '([0-9]+)(m|h)'
                              strategyName:
                                  type: string
                                  enum: ["fifo", "fifo-plus-older"]
                              strategySpec:
                                  type: object
                                  properties:
                                      keepLastOlderNotMoreThan:
                                          type: string
                                      maxOlderCopies:
                                          type: integer
                              healthSecretRef:
                                  type: object
                                  required: ["name", "entry"]
                                  properties:
                                      name:
                                          type: string
                                      entry:
                                          type: string
                              accessControl:
                                  type: array
                                  items:
                                      type: object
                                      properties:
                                          userName:
                                              type: string
                                          roles:
                                              type: array
                                              items:
                                                  type: string
                                                  enum: ["collectionManager", "backupUploader", "backupDownloader", "uploadsAnytime"]


          additionalPrinterColumns:
            - name: "Strategy"
              type: string
              jsonPath: .spec.strategyName

            - name: "Filename template"
              type: string
              jsonPath: .spec.filenameTemplate

            - name: "Max backups count"
              type: string
              jsonPath: .spec.maxBackupsCount

            - name: "Max collection size"
              type: string
              jsonPath: .spec.maxCollectionSize

---
apiVersion: apiextensions.k8s.io/v1
kind: "CustomResourceDefinition"
metadata:
    name: "backupusers.backups.riotkit.org"
    annotations:
        helm.sh/resource-policy: keep
        argocd.argoproj.io/sync-options: Prune=false
spec:
    group: "backups.riotkit.org"
    scope: "Namespaced"
    names:
        plural: "backupusers"
        singular: "backupuser"
        kind: "BackupUser"
        shortNames:
            - "brusers"
            - "bru"
        categories:
            - "backuprepository"
    versions:
        - name: v1alpha1
          served: true
          storage: true

          schema:
              openAPIV3Schema:
                  type: object
                  required: ["spec"]
                  properties:
                      spec:
                          type: object
                          required: ["email", "roles"]
                          properties:
                              email:
                                  type: string
                              deactivated:
                                  type: boolean
                              organization:
                                  type: string
                              about:
                                  type: string
                              password:  # todo: remove
                                  type: string
                              passwordFromRef:
                                  type: object
                                  required: ["name", "entry"]
                                  properties:
                                      name:
                                          type: string
                                      entry:
                                          type: string
                              restrictByIP:
                                  type: array
                                  items:
                                      type: string
                              roles:
                                  type: array
                                  items:
                                      type: string
                                      enum: ["collectionManager", "usersManager", "systemAdmin", "backupUploader", "backupDownloader", "uploadsAnytime"]


          additionalPrinterColumns:
              - name: Email
                type: string
                jsonPath: .spec.email

              - name: Organization
                type: string
                jsonPath: .spec.organization

              - name: Is deactivated
                type: boolean
                jsonPath: .spec.deactivated
