{{- if .Values.route.enabled -}}
{{- with .Values.route -}}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
    name: {{ include "backup-repository-server.fullname" . }}
spec:
    host: {{ .host }}
    port:
        targetPort: http
    to:
        kind: Service
        name: {{ include "backup-repository-server.fullname" . }}
        weight: 100
    wildcardPolicy: None
    {{- with .yaml -}}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
