{{- if .Values.secrets.create }}
{{ if eq .Values.secrets.type "sealedSecrets" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: {{ .Values.secrets.name }}
spec:
{{- with .Values.secrets.spec }}
    encryptedData:
{{- range $key, $value := . }}
        {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}


{{ end }}
{{- end }}
