{{- if .Values.secrets.create }}
{{ if eq .Values.secrets.type "plain" }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.secrets.name }}
{{- with .Values.secrets.spec }}
data:
{{- range $key, $value := . }}
    {{ $key }}: "{{ $value | b64enc }}"
{{- end }}
{{- end }}

{{ end }}

# {{ required "You need to specify .secrets.spec.BR_JWT_SECRET_KEY" .Values.secrets.spec.BR_JWT_SECRET_KEY }}
{{- end }}
