{{ if eq .Values.secretsType "plain" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: {{ include "backup-repository-server.fullname" . }}-credentials
spec:
    encryptedData:
{{- range $key, $value := . }}
        {{ $key }}: "{{ $value }}"
{{- end }}
{{ end }}
