{{ if eq .Values.secretsType "plain" }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "backup-repository-server.fullname" . }}-credentials
{{- with .Values.secrets }}
data:
{{- range $key, $value := . }}
    {{ $key }}: "{{ $value | b64enc }}"
{{- end }}
{{- end }}

{{ end }}

# {{ required "You need to specify .secrets.BR_JWT_SECRET_KEY" .Values.secrets.BR_JWT_SECRET_KEY }}
