{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ include "backup-repository-server.serviceAccountName" . }}
    labels:
        {{- include "backup-repository-server.labels" . | nindent 8 }}
  {{- with .Values.serviceAccount.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- end }}
