version: org.riotkit.rkd/yaml/v1
imports: []

environment:
    BROWSER_BIN: "chromium"
    PHP_BIN: "php"

tasks:
    :test:
        description: Run End-To-End tests with Behat
        arguments:
            "--filter":
                help: "Filter tests by partial name"
            "--docker":
                help: "Test dockerized applications"
                action: store_true
            "--tags":
                help: "Behat tags"
            "--params":
                help: "Extra Behat arguments"
        steps: |
            params=""
            config_path="./behat.yml"

            if [[ $ARG_TAGS ]]; then
                params=" --tags ${ARG_TAGS} "
            fi

            if [[ $ARG_FILTER ]]; then
                params=" ${params} --name='${ARG_FILTER}' "
            fi

            if [[ $ARG_DOCKER == "True" ]]; then
                config_path="./behat.docker.yml"
                export TEST_ENV_TYPE=docker
            fi

            set -x;
            eval "${PHP_BIN} ./vendor/bin/behat -c ${config_path} -f pretty -o std -f junit -o build/results-xml ${params} ${ARG_PARAMS}"

    :install:
        description: Install
        steps: composer install --no-progress

    #
    # Runs a native browser (without a docker container)
    #
    :browser:spawn-without-docker:
        description: Run Chromium browser
        steps:
            - rm -rf .rkd/browser-profile
            - $BROWSER_BIN --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --user-data-dir=.rkd/browser-profile
