version: org.riotkit.rkd/yaml/v1
imports: []

environment:
    BROWSER_BIN: "chromium"

tasks:
    :test:
        description: Run End-To-End tests with Behat
        steps: ./vendor/bin/behat

    :test:in-docker:
        description: Run End-To-End tests with Behat
        arguments:
            "--filter":
                help: "Filter tests by partial name"
        steps: |
            params=""

            if [[ $ARG_FILTER ]]; then
                params=" --name='${ARG_FILTER}' "
            fi

            TEST_ENV_TYPE=docker eval "./vendor/bin/behat -c ./behat.docker.yml -f pretty -o std -f junit -o build/results-xml ${params}"

    :install:
        description: Install
        steps: composer install --no-progress

    #
    # Runs a native browser (without a docker container)
    #
    :browser:spawn-without-docker:
        description: Run Chromium browser
        steps:
            - rm -rf .rkd/browser-profile
            - $BROWSER_BIN --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --user-data-dir=.rkd/browser-profile
