# Default values for backup-repository-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

settings:
    healthCode: changeme

# supported values: sealedSecrets, plain
# when using sealedSecrets please paste already ENCRYPTED secrets into `.secrets` section
secretsType: plain

secrets:
    BR_JWT_SECRET_KEY: "" # leave empty to auto-generate, will be stored in `kind: Secret`
    BR_DB_HOSTNAME: "..."
    BR_DB_PASSWORD: "..."
    BR_DB_USERNAME: "..."
    BR_DB_NAME: "..."
    BR_DB_PORT: "5432"

env: []
    # BR_USE_GOOGLE_CLOUD=false
    # todo: list all environment variables there

image:
    repository: ghcr.io/riotkit-org/backup-repository
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

podAnnotations: {}
podSecurityContext: {}

securityContext:
    capabilities:
        drop: ["ALL"]
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    # runAsUser: 1000

service:
    type: ClusterIP
    port: 80

ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
        - host: backups.example.org
          paths:
              - path: /
                pathType: ImplementationSpecific
    tls: []

route:
    enabled: false
    host: backups.example.org
    yaml: {}  # extra settings on spec level e.g. put TLS settings there

resources:
    limits:
        cpu: 2
        memory: 1Gi
    requests:
        cpu: 50m
        memory: 128Mi

autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
