version: org.riotkit.rkd/yaml/v1
imports: []

environment:
    PHP_BIN: "php"

tasks:
    :test:
        description: Run API tests
        arguments:
            "--filter":
                help: "Execute only selected test case. Examples: Features/Security/FeatureOnlyOneFileAllowedToUploadCest, BackupCollectionListingCest, RegistryListingCest:testListingAllFiles"
            "--docker":
                action: "store_true"
                help: "Tests application that is in docker"
        steps:
            - mkdir -p build
            - rm ./tests/Functional/_output/*.html build/*.json 2>/dev/null || true
            - |
                config_path="codeception.yml"
                if [[ $ARG_DOCKER == "True" ]]; then
                    export TEST_ENV_TYPE=docker
                    config_path="codeception.local-docker.yml"
                fi

                export SYMFONY_DEPRECATIONS_HELPER=weak
                ${PHP_BIN} ./vendor/bin/codecept run --html=build/api.html --xml=build/api.junit.xml --config=${config_path} functional ${ARG_FILTER};

            - cp -pr ./tests/Functional/_output/* build/

    :install:
        description: Install
        steps: composer install --no-progress
