name: Release
on:
    push:
        tags:
            - '*'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: "riotkit-org/backup-repository"

permissions: write-all

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19

            - name: Build
              run: "make build"

            - name: Release binaries to GitHub releases
              uses: goreleaser/goreleaser-action@v2
              with:
                  distribution: goreleaser
                  version: latest
                  args: release --rm-dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - uses: actions/upload-artifact@v2
              with:
                  name: binary
                  path: .build/backup-repository

    release-docker:
        runs-on: ubuntu-latest
        needs: ["build"]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: actions/download-artifact@v2
              with:
                  name: binary
                  path: .build/

            - name: Log in to the Container registry
              uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@e6428a5c4e294a61438ed7f43155db912025b6b3
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            - name: Build and release to container registry
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: ${{ startsWith(github.ref, 'refs/tags/') }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

    chart-release:
        runs-on: ubuntu-latest
        needs: ["build", "release-docker"]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Configure Git
              run: |
                  git config user.name "$GITHUB_ACTOR"
                  git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

            - name: Publish Helm chart
              uses: stefanprodan/helm-gh-pages@master
              with:
                  token: "${{ secrets.GH_RW_TOKEN }}"
                  charts_dir: helm
                  charts_url: https://riotkit-org.github.io/helm-of-revolution
                  owner: riotkit-org
                  repository: helm-of-revolution
                  branch: gh-pages
                  target_dir: ./
                  commit_username: "${{ env.GITHUB_ACTOR }}"
                  commit_email: "${{ env.GITHUB_ACTOR }}@users.noreply.github.com"

                  app_version: "${{github.ref_name}}"
                  chart_version: "${{github.ref_name}}"
